### PR TITLE
Added specs for Inline Blocks

### PR DESCRIPTION
**Pull request by Devorein**
EquationFormat formatting was missing.

### CODE REVIEW

**Comment by phuctm97** [comment]
Hi @Devorein, thank you a lot for the PR! Mind rebasing your branch? I just added a Github check.

**Comment by phuctm97** [comment]
Thanks for updating. It would be great if you can add an example or just yields of how an equation can be represented `["e", string]` doesn't really show how an equation looks like. How the `string` will likely be formatted?

**Comment by Devorein** [comment]
Good idea. On it.

**Comment by Devorein** [comment]
@phuctm97 Can you please direct me on how to show an example for equation format in the readme. This is a special type of formatting like Inline Date, Person, Page, and I don't see any examples for those as well.

**Comment by phuctm97** [comment]
> @phuctm97 Can you please direct me on how to show an example for equation format in the readme. This is a special type of formatting like Inline Date, Person, Page, and I don't see any examples for those as well.

Sure, sorry for the confusion. There's really no standard for examples in this specification. The easiest way is to capture a screen with several equations and log an object how these equations are represented in your proposals. Add that next to the current example or how you feel easier for readers to understand.

Thanks for pointing out that PageFormat, UserFormat, and ExternalLinkFormat don't have examples yet, will add these soon!

**Comment by phuctm97** [comment]
How was it @Devorein? Just want to check in if you need more helps to merge this.

**Comment by Devorein** [comment]
@phuctm97 I've added examples and new specs for inline content. Could you please check and report?

**Comment by phuctm97** [comment]
This is really awesome. However, look like you were using npm, it generated package-lock.json and unexpected change to yarn.lock. Please help revert changes of these 2 files and use yarn instead.

**Comment by Devorein** [comment]
@phuctm97 I've replaced npm with yarn and distinguished between two different types for contents in the spec.

**Comment by phuctm97** [comment]
Look amazing! Merging.

**Comment by phuctm97** [comment]
Thank you for contributing @Devorein. Adding you to the list of contributors in the frontpage.

**Pull request merged**
